charts:
  - name: secret-replicator
    imagePrefix: daewok/
    repo:
      git: daewok/helm-charts
      published: https://daewok.github.io/helm-charts
    paths:
      - ../requirements.txt
      - ../k8s_secret_replicator.py
    images:
      k8s-secret-replicator:
        contextPath: ..
        dockerfilePath: ../Dockerfile
        valuesPath: image
        paths:
          - ../requirements.txt
          - ../k8s_secret_replicator.py
