apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secret-replicator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "secret-replicator.name" . }}
    helm.sh/chart: {{ include "secret-replicator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "secret-replicator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "secret-replicator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "secret-replicator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: SECRET_REPLICATOR_MANGED_LABEL_NAME
              value: {{ .Values.managedLabelName | quote }}
            - name: SECRET_REPLICATOR_LABEL_NAMES
              value: {{ join ";" .Values.replicationLabelNames | quote }}
            - name: SECRET_REPLICATOR_NAMESPACE_TO_WATCH
              value: {{ .Release.Namespace | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
