# Default values for secret-replicator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: daewok/k8s-secret-replicator
  tag: generated-by-chartpress
  pullPolicy: IfNotPresent

nameOverride: ''
fullnameOverride: ''

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

replicationLabelNames:
  - secret-replicator.daewok/replicate

managedAnnotationName: secret-replicator.daewok/managed

rbac:
  create: true

serviceAccount:
  create: true
  name:
